[project]
name = "trendwise"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "kaggle>=1.6.17",
    "pydantic>=2.10.5",
    "pydantic-settings>=2.7.1",
]
